configs:
  - key: "companyName"
    value: "Roadmap.IO"
    isActive: true
    isProtected: false
  - key: "maintenanceBannerIsActive"
    value: false
    isActive: true
    isProtected: true
  - key: "maintenanceBannerText"
    value: "The portal is currently undergoing maintenance. We kindly request that you refrain from making any transactions or creating new roadmaps at this time to avoid potential errors. However, you can still browse and explore existing roadmaps without any issues."
    isActive: true
    isProtected: true
  - key: "publicHomePageBannerIsActive"
    value: true
    isActive: true
    isProtected: false
  - key: "publicHomePageBannerText"
    value: "Do not pay lacs for your personlized roadmaps. Unlock access to almost all companies' exclusive content. Stay ahead with the most accurate insights and industry-leading efficiency. Your roadmap to success starts here."
    isActive: true
    isProtected: false
  - key: "supportEmailId"
    value: "support@roadmap.io"
    isActive: true
    isProtected: false
  - key: "publicHomePageFeatures"
    value: >
      [
        {
          "icon": null,
          "title": "Company-Specific Preparation (For Interns to All levels)",
          "description": "Select your dream company and role to receive a personalized roadmap based on real interview patterns."
        },
        {
          "icon": null,
          "title": "AI-Powered Insights",
          "description": "Curated by real-world top AI models and updated weekly using past interview data and industry trends."
        },
        {
          "icon": null,
          "title": "High Accuracy",
          "description": "Each roadmap includes real, previously asked questions tailored to your target company and role."
        },
        {
          "icon": null,
          "title": "Roadmaps for both IT and Non-IT",
          "description": "Includes hand-picked solutions and resources to help you follow the roadmap efficiently for your IT or Non-IT career."
        },
        {
          "icon": null,
          "title": "Affordable & Valuable",
          "description": "Get top-tier prep material at a fraction of coaching costs—no overpriced packages."
        },
        {
          "icon": null,
          "title": "One-Click Kickstart",
          "description": "Login, select, and go. Start your prep journey in seconds with instant roadmap access."
        }
      ]
    isActive: true
    isProtected: false